server:
  port: 8080

spring:
  datasource:
    # TODO: 나중에 실제 DB 정보로 채워넣어야 함
    url: ${DB_URL:jdbc:mysql://localhost:3306/playprobie}
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false # 운영에선 SQL 로그 끄기

logging:
  level:
    com.playprobie: INFO
    org.springframework: INFO

ai:
  server:
    url: ${AI_SERVER_URL}